"use client";

import { useState } from "react";
import { useRepoStore } from "@/store/repoStore";

export default function ExportCard() {
  const { data } = useRepoStore();
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    if (!data) return;
    setExporting(true);

    try {
      // Dynamic import to avoid SSR issues
      const jsPDF = (await import("jspdf")).default;
      const html2canvas = (await import("html2canvas")).default;

      const dashboard = document.getElementById("dashboard");
      if (!dashboard) return;

      const canvas = await html2canvas(dashboard, {
        backgroundColor: "#07071a",
        scale: 1.5,
        logging: false,
        useCORS: true,
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "landscape",
        unit: "px",
        format: [canvas.width, canvas.height],
      });

      pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height);

      // Add summary text page
      pdf.addPage();
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(20);
      pdf.setTextColor(0, 245, 255);
      pdf.text("RepoRadar Analysis Report", 40, 50);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(12);
      pdf.setTextColor(180, 180, 220);
      pdf.text(`Repository: ${data.meta.full_name}`, 40, 80);
      pdf.text(`Health Score: ${data.healthScore.total}/100 (${data.healthScore.label})`, 40, 100);
      pdf.text(`Bus Factor: ${data.busFactor.busFactor} (${data.busFactor.riskLevel} RISK)`, 40, 120);
      pdf.text(`Contributors: ${data.contributors.length}`, 40, 140);
      pdf.text(`Stars: ${data.meta.stars.toLocaleString()}`, 40, 160);
      pdf.text(`Avg PR Merge Time: ${data.prStats.avgMergeTimeDays} days`, 40, 180);
      pdf.text(`Generated by RepoRadar · ${new Date().toLocaleDateString()}`, 40, 220);

      pdf.save(`reporadar-${data.meta.full_name.replace("/", "-")}.pdf`);
    } catch (err) {
      console.error("Export error:", err);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="glass-card bounce-card p-5 flex flex-col">
      <div className="cyber-label">⬒ EXPORT REPORT</div>

      <p className="text-xs mb-4 flex-1" style={{ color: "var(--text-secondary)" }}>
        Download a comprehensive PDF report with all metrics, charts and insights.
      </p>

      <button
        onClick={handleExport}
        disabled={exporting}
        className="btn-cyber w-full justify-center"
        style={{ opacity: exporting ? 0.7 : 1 }}
      >
        {exporting ? (
          <>
            <span className="animate-spin-slow">◈</span> GENERATING...
          </>
        ) : (
          <>
            ⬒ EXPORT PDF
          </>
        )}
      </button>

    </div>
  );
}
